### PR TITLE
pass enforce_sorted to False

### PR DESCRIPTION
**Pull request by JoanFM**
This is a PR as much as it is a question, according to the documentation on `pack_padded_sequence`, by default it understands that their input comes sorted from longest sentence to shortest.

```python
        enforce_sorted (bool, optional): if ``True``, the input is expected to
            contain sequences sorted by length in a decreasing order. If
            ``False``, the input will get sorted unconditionally. Default: ``True``.
```

I cannot see where is this guaranteed at data loading time to ensure that every batch is properly processed, could this be an issue? I have reproduced your results, but I have seen differences when embedding sentences alone or in a batch, and what I have observed is that embeddings in a batch seemed to be mixed up.

### CODE REVIEW

**Comment by fartashf** [comment]
Hi Joan,
Data is always sorted by the length of the caption using this line:
https://github.com/fartashf/vsepp/blob/9b2ccba2a0362f43ed16b8e2d9c472f05454d4e5/data.py#L254-L256

I did not know about the `enforce_sorted` flag which could be an easier replacement for the above line.

**Comment by JoanFM** [comment]
> Hi Joan,
> Data is always sorted by the length of the caption using this line:
> https://github.com/fartashf/vsepp/blob/9b2ccba2a0362f43ed16b8e2d9c472f05454d4e5/data.py#L254-L256
> 
> I did not know about the `enforce_sorted` flag which could be an easier replacement for the above line.

Yes, I found in my implementation I was sorting but then not getting the sort back, setting this flag releases me from doing the sort and reconsidering back inside a batch.

**Comment by fartashf** [comment]
Thanks for the PR but because of the particular `collate_fn` implementation, I don't think the addition of `enforce_sort=False` would add anything. I'd rather not merge this but the explanation in this PR might help others. Thank you.

**Comment by JoanFM** [comment]
> Thanks for the PR but because of the particular `collate_fn` implementation, I don't think the addition of `enforce_sort=False` would add anything. I'd rather not merge this but the explanation in this PR might help others. Thank you.

Maybe we can close this and refer to the closed issue in an open issue?

**Pull request closed without merging**
